version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocheckcompilerdirectives
    - nilerr
    - nolintlint
    - usetesting
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    usetesting:
      os-temp-dir: true

formatters:
  enable:
    - gofmt
